image: Visual Studio 2017
platform: x64
build:
  verbosity: minimal

install:
  - set QTDIR=C:\Qt\5.9\msvc2017_64
  - set PATH=%PATH%;%QTDIR%\bin

build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat" amd64
  - qmake SkauTan.pro
  - nmake
